--- #YAML:1.0
name:               Parse-ExuberantCTags-Merge
version:            1.00
abstract:           Efficiently merge large exuberant ctags files
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::XSAccessor:  1.03
    File::Copy:         0
    File::Temp:         0
    Sort::External:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
